# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0d4c2e1e935fdf824115a259ff5a9a31cc25df69dd37f1d58828cd752665fa6ed3ea97f3f33be6b4454317ee9239f825dceb577b74ac219548f538d8f20f5edd

test:
  secret_key_base: 3b6b44f3f4006ebc81c4e91d8456f614f1a538ccfea0c1da4588e2450a4c5eec2146775cec24ed1d913f71ee9df6510cd15616c0cbcb6545475ec887117536cc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
